language: python
install:
  - pip install tox
script:
  - tox
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=dj12-py26
  - TOXENV=dj12
  - TOXENV=dj13
  - TOXENV=dj14
  - TOXENV=dj15
  - TOXENV=dj16
  - TOXENV=dj15-py32
  - TOXENV=dj15-py33
  - TOXENV=dj15-py33-postgres
  - TOXENV=py26-wt1x
  - TOXENV=py27-clocale
  - TOXENV=py33-clocale
  - TOXENV=py34-clocale
