language: python
python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
  - "pypy"

env:
  - DJANGO_VERSION=1.2.7
  - DJANGO_VERSION=1.3.7
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.5.1

matrix:
    include:
        - python: "2.7"
          env: DJANGO_VERSION=1.5.1 OLD_WEBTEST=1
    exclude:
        - python: "3.2"
          env: DJANGO_VERSION=1.2.7
        - python: "3.2"
          env: DJANGO_VERSION=1.3.7
        - python: "3.2"
          env: DJANGO_VERSION=1.4.5
        - python: "3.3"
          env: DJANGO_VERSION=1.2.7
        - python: "3.3"
          env: DJANGO_VERSION=1.3.7
        - python: "3.3"
          env: DJANGO_VERSION=1.4.5
        - python: "pypy"
          env: DJANGO_VERSION=1.2.7
        - python: "pypy"
          env: DJANGO_VERSION=1.3.7


# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install django==$DJANGO_VERSION
  - if [[ $OLD_WEBTEST ]]; then pip install 'WebTest < 2.0'; else pip install WebTest; fi
  - python setup.py install

# command to run tests, e.g. python setup.py test
script: python django_webtest_tests/runtests.py
