
language: python
python: 3.5  # this is needed to get travis to have python3.5 as well

sudo: false

addons:
  postgresql: "9.3"
services:
  - postgresql
before_script:
  - psql -c 'create database django_webtest_tests;' -U postgres

install:
  - pip install tox
script:
  - tox
env:
  - TOXENV=pypy-django19-std
  - TOXENV=py26-django13-std
  - TOXENV=py26-django14-std
  - TOXENV=py26-django15-std
  - TOXENV=py26-django16-std
  - TOXENV=py27-django15-std
  - TOXENV=py27-django15-clocale
  - TOXENV=py27-django15-postgres
  - TOXENV=py27-django16-std
  - TOXENV=py27-django16-clocale
  - TOXENV=py27-django16-postgres
  - TOXENV=py27-django17-std
  - TOXENV=py27-django17-clocale
  - TOXENV=py27-django17-postgres
  - TOXENV=py27-django18-std
  - TOXENV=py27-django18-clocale
  - TOXENV=py27-django18-postgres
  - TOXENV=py27-django19-std
  - TOXENV=py27-django19-clocale
  - TOXENV=py27-django19-postgres
  - TOXENV=py27-django110-std
  - TOXENV=py27-django110-clocale
  - TOXENV=py27-django110-postgres
  - TOXENV=py27-django111-std
  - TOXENV=py27-django111-clocale
  - TOXENV=py27-django111-postgres
  - TOXENV=py34-django15-std
  - TOXENV=py34-django15-clocale
  - TOXENV=py34-django15-postgres
  - TOXENV=py34-django16-std
  - TOXENV=py34-django16-clocale
  - TOXENV=py34-django16-postgres
  - TOXENV=py34-django17-std
  - TOXENV=py34-django17-clocale
  - TOXENV=py34-django17-postgres
  - TOXENV=py34-django18-std
  - TOXENV=py34-django18-clocale
  - TOXENV=py34-django18-postgres
  - TOXENV=py34-django19-std
  - TOXENV=py34-django19-clocale
  - TOXENV=py34-django19-postgres
  - TOXENV=py34-django110-std
  - TOXENV=py34-django110-clocale
  - TOXENV=py34-django110-postgres
  - TOXENV=py34-django111-std
  - TOXENV=py34-django111-clocale
  - TOXENV=py34-django111-postgres
  - TOXENV=py35-django18-std
  - TOXENV=py35-django18-clocale
  - TOXENV=py35-django18-postgres
  - TOXENV=py35-django19-std
  - TOXENV=py35-django19-clocale
  - TOXENV=py35-django19-postgres
  - TOXENV=py35-django110-std
  - TOXENV=py35-django110-clocale
  - TOXENV=py35-django110-postgres
  - TOXENV=py35-django111-std
  - TOXENV=py35-django111-clocale
  - TOXENV=py35-django111-postgres
